// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXX9IVKBMO1nsZP5PX7GhBcVWTKZTCPIE',
    appId: '1:458703033849:web:5fb5b56b503795e1a75928',
    messagingSenderId: '458703033849',
    projectId: 'textly-52b85',
    authDomain: 'textly-52b85.firebaseapp.com',
    storageBucket: 'textly-52b85.appspot.com',
    measurementId: 'G-ER2BRWV5BR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa56G3wnC8uetUPPSdG8fDVVp_u29Rmac',
    appId: '1:458703033849:android:94c32fb0204e8d6aa75928',
    messagingSenderId: '458703033849',
    projectId: 'textly-52b85',
    storageBucket: 'textly-52b85.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD599y9GPL6K3rEchuqA7FxUXO7J5DqFA',
    appId: '1:458703033849:ios:bd8c64364137a0b5a75928',
    messagingSenderId: '458703033849',
    projectId: 'textly-52b85',
    storageBucket: 'textly-52b85.appspot.com',
    iosBundleId: 'com.example.weChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCD599y9GPL6K3rEchuqA7FxUXO7J5DqFA',
    appId: '1:458703033849:ios:bd8c64364137a0b5a75928',
    messagingSenderId: '458703033849',
    projectId: 'textly-52b85',
    storageBucket: 'textly-52b85.appspot.com',
    iosBundleId: 'com.example.weChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXX9IVKBMO1nsZP5PX7GhBcVWTKZTCPIE',
    appId: '1:458703033849:web:8d44393ad20371fca75928',
    messagingSenderId: '458703033849',
    projectId: 'textly-52b85',
    authDomain: 'textly-52b85.firebaseapp.com',
    storageBucket: 'textly-52b85.appspot.com',
    measurementId: 'G-2CCJJJL2LL',
  );
}
